language: ruby
before_install:
  - uname -a
  - sudo apt-cache search udis
  - sudo apt-get install udis86-dev
  - gem install ffi rubygems-tasks rspec yard
rvm:
  - 1.9.3
  - 2.0.0
  - rbx-18mode
  - rbx-19mode
matrix:
  allow_failures:
    - rvm: rbx-18mode
    - rvm: rbx-19mode
script: rake test
