language: ruby
before_install:
  - sudo apt-get install udis86-dev yasm
  - gem install ffi rubygems-tasks rspec yard
rvm:
  - 2.5
  - 2.6
  - 2.7
  - rbx-18mode
  - rbx-19mode
matrix:
  allow_failures:
    - rvm: rbx-18mode
    - rvm: rbx-19mode
script: rake test
