# Generated by jeweler
# DO NOT EDIT THIS FILE DIRECTLY
# Instead, edit Jeweler::Tasks in Rakefile, and run the gemspec command
# -*- encoding: utf-8 -*-

Gem::Specification.new do |s|
  s.name = %q{ffi-udis86}
  s.version = "0.1.0"

  s.required_rubygems_version = Gem::Requirement.new(">= 0") if s.respond_to? :required_rubygems_version=
  s.authors = ["Postmodern"]
  s.date = %q{2010-09-19}
  s.description = %q{Ruby FFI bindings for udis86, a x86 and x86-64 disassembler.}
  s.email = %q{postmodern.mod3@gmail.com}
  s.extra_rdoc_files = [
    "ChangeLog.md",
    "LICENSE.txt",
    "README.md"
  ]
  s.files = [
    ".gitignore",
    ".specopts",
    ".yardopts",
    "ChangeLog.md",
    "Gemfile",
    "Gemfile.lock",
    "LICENSE.txt",
    "README.md",
    "Rakefile",
    "ffi-udis86.gemspec",
    "lib/ffi/udis86.rb",
    "lib/ffi/udis86/operand.rb",
    "lib/ffi/udis86/operand_pointer.rb",
    "lib/ffi/udis86/operand_value.rb",
    "lib/ffi/udis86/types.rb",
    "lib/ffi/udis86/ud.rb",
    "lib/ffi/udis86/udis86.rb",
    "lib/ffi/udis86/version.rb",
    "lib/udis86.rb",
    "spec/helpers/files.rb",
    "spec/helpers/files/operands_index_scale",
    "spec/helpers/files/operands_index_scale.s",
    "spec/helpers/files/operands_memory",
    "spec/helpers/files/operands_memory.s",
    "spec/helpers/files/operands_offset",
    "spec/helpers/files/operands_offset.s",
    "spec/helpers/files/operands_simple",
    "spec/helpers/files/operands_simple.s",
    "spec/helpers/files/simple",
    "spec/helpers/files/simple.s",
    "spec/helpers/operands.rb",
    "spec/operand_spec.rb",
    "spec/spec_helper.rb",
    "spec/ud_spec.rb",
    "spec/udis86_spec.rb"
  ]
  s.has_rdoc = %q{yard}
  s.homepage = %q{http://github.com/sophsec/ffi-udis86}
  s.require_paths = ["lib"]
  s.requirements = ["udis86, 1.7 or greater"]
  s.rubygems_version = %q{1.3.7}
  s.summary = %q{Ruby FFI bindings for udis86, a x86 and x86-64 disassembler.}
  s.test_files = [
    "spec/helpers/files.rb",
    "spec/helpers/operands.rb",
    "spec/operand_spec.rb",
    "spec/spec_helper.rb",
    "spec/ud_spec.rb",
    "spec/udis86_spec.rb"
  ]

  if s.respond_to? :specification_version then
    current_version = Gem::Specification::CURRENT_SPECIFICATION_VERSION
    s.specification_version = 3

    if Gem::Version.new(Gem::VERSION) >= Gem::Version.new('1.2.0') then
      s.add_runtime_dependency(%q<ffi>, ["~> 0.6.0"])
      s.add_development_dependency(%q<bundler>, ["~> 1.0.0"])
      s.add_development_dependency(%q<rake>, ["~> 0.8.7"])
      s.add_development_dependency(%q<jeweler>, ["~> 1.5.0.pre"])
      s.add_development_dependency(%q<rspec>, ["~> 1.3.0"])
    else
      s.add_dependency(%q<ffi>, ["~> 0.6.0"])
      s.add_dependency(%q<bundler>, ["~> 1.0.0"])
      s.add_dependency(%q<rake>, ["~> 0.8.7"])
      s.add_dependency(%q<jeweler>, ["~> 1.5.0.pre"])
      s.add_dependency(%q<rspec>, ["~> 1.3.0"])
    end
  else
    s.add_dependency(%q<ffi>, ["~> 0.6.0"])
    s.add_dependency(%q<bundler>, ["~> 1.0.0"])
    s.add_dependency(%q<rake>, ["~> 0.8.7"])
    s.add_dependency(%q<jeweler>, ["~> 1.5.0.pre"])
    s.add_dependency(%q<rspec>, ["~> 1.3.0"])
  end
end

